Feat/cluster
Dessia-tech/dessia_common pull request #297
Opened 2022-07-13 11:15 UTC by Tanguylo

* **What kind of changes does this PR introduce?** 
- [x] new features

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
- [x] Yes: 
       - New subclasses of DessiaObject : HeterogeneousList(DessiaObject) and CategorizedList(HeterogeneousList)
       - No changes required in users' applications
       - New practices for handling lists of data and creating subsets of datasets

* **Other information**:
In next releases, HeterogeneousLists will be equiped with all identified datas mining useful technologies

2022-07-19 10:00 UTC, masfaraud requested changes

2022-07-19 15:36 UTC, Tanguylo commented on dessia_common/templates.py
> +heterogeneouslist_markdown_template = Template('''
Removed for the moment.
I made this to prepare the markdown implementation.

2022-07-19 16:03 UTC, Tanguylo commented on dessia_common/tests.py
> +class ClusTesterD1(DessiaObject):
Changed to RandDataDn (n in range(10))

2022-07-19 16:36 UTC, Tanguylo commented on dessia_common/workflow/blocks.py
> +class Concatenate(Block):
Done for dict (uncertain behavior) and HLists.
Any idea for other type ?

2022-07-19 16:39 UTC, Tanguylo commented on tests/_simulation_workflow.py
> +import dessia_common.typings as dct
file removed because I don't know what it is

2022-07-25 16:38 UTC, masfaraud approved these changes

2022-07-26 17:56 UTC, masfaraud approved these changes

2022-08-08 14:11 UTC, masfaraud approved these changes

2022-08-08 14:11 UTC, merged