add some functions to MarkdownWriter class
Dessia-tech/dessia_common pull request #562
Opened 2023-03-15 17:26 UTC by younesdessia

* **What kind of changes does this PR introduce?** 
- [ ] Bug fix
- [X] new features
- [ ] performance 
- [ ] docs update

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
- [ ] Yes:
- [X] No

* **Other information**:

2023-03-21 18:19 UTC, Tanguylo reviewed
Just change something in docstrings from other codes but don't increase min note please :)

2023-03-21 21:38 UTC, younesdessia commented on code_pylint.py
> +    "wrong-spelling-in-docstring": 180,
it's good, it's done !

2023-03-22 08:51 UTC, Tanguylo commented on dessia_common/tests.py
> +        """ Dummy property for some tests. """
;)

2023-03-22 08:51 UTC, Tanguylo approved these changes

2023-03-24 11:07 UTC, GhislainJ requested changes
Just some small changes

2023-03-24 11:56 UTC, GhislainJ approved these changes

2023-03-24 11:56 UTC, merged