feat/rename load DessiaObject methods
Dessia-tech/dessia_common pull request #577
Opened 2023-04-13 08:17 UTC by younesdessia

* **What kind of changes does this PR introduce?** 
- [ ] Bug fix
- [X] new features
- [ ] performance 
- [ ] docs update

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
- [X] Yes:
- [ ] No

use from_json and from_json_stream to download a dessiaobject from a file and a stream
* **Other information**:

https://github.com/Dessia-tech/dessia_common/issues/563

2023-04-13 12:23 UTC, GhislainJ reviewed
You should add backwards compatibility in order to warn users that are still using old methods.

Have you checked that it doesn't break anything on backend and frontend side ?

2023-04-13 13:19 UTC, younesdessia commented
I added a warning, 
I will check if there are not problem with back/front

2023-04-18 08:44 UTC, GhislainJ requested changes

2023-04-18 08:44 UTC, GhislainJ commented on dessia_common/core.py
>          dict_ = json.loads(stream.read().decode('utf-8'))
In order to properly implement backward compatibility, you should call the new function here since they are the same.

2023-04-18 08:44 UTC, GhislainJ commented on dessia_common/core.py
> +        with open(filepath, 'r', encoding='utf-8') as file:
same here

2023-04-18 11:45 UTC, GhislainJ approved these changes

2023-04-20 15:35 UTC, GhislainJ requested changes

2023-04-20 15:35 UTC, GhislainJ commented on dessia_common/core.py
> -            msg = f"Object of type '{classname}' is not subscriptable. Failed to deeply get '{attr}' from it"
subscriptable could be added to dictionnary

2023-04-20 15:35 UTC, GhislainJ commented on dessia_common/typings.py
> -    """ Typing that denotes a classmethod of class T. """
classmethod could be added to dictionnary

2023-04-26 09:45 UTC, GhislainJ approved these changes

2023-04-26 09:45 UTC, merged